### ISSUE TITLE
Should unzip1..unzip5 be added to R7RS large?

### ISSUE THREAD

**Issue by imfrancisd** [scheme-requests-for-implementation/srfi-1#1]
### Too Unusual

The unzippers in SRFI-1 are just too weird compared to the other list functions.

Scheme doesn't have zip1..zip5 or map1..map5 or other functions with numbers at the end of their names. Also, a lot of Scheme list functions do not return multiple values, but unzip1..unzip5 do and these unzippers must be used in special ways (call-with-values and/or receive).

I know that the discussion for this SRFI ended a long time ago, but according to the thread [SRFI1: 90 days to discuss 89 procedures?](http://srfi.schemers.org/srfi-1/mail-archive/msg00000.html), it seems that there wasn't much time for discussion at all.

### Background

I don't know if this is the right place to put this comment, but the [WG2 Consent Docket](http://trac.sacrideo.us/wg/wiki/ConsentDocket) states:
> The following items will be approved without a formal vote unless someone objects, in which case they will be moved to another docket. See WG2Dockets for other dockets.

And then later, it states:
> SRFI 1, list library: As written, but excluding cons, pair?, null?, car, cdr, caar ... cddddr, set-car!, set-cdr!, list, append, reverse, length, list-ref, map, for-each, memq, memv, member, assq, assv, assoc, which are all in the (scheme base) and (scheme cxr) libraries in a SRFI-1-compatible way. Specification bug in SRFI 1: any, every, and list-index should omit the words "and returning a boolean result". [Red]

*I'm not sure if I'm allowed to object (I'm not even sure if anyone will read this), but here goes nothing. :-)*

**Comment by imfrancisd** [comment]
In case anyone is listening, may I suggest something like this instead?
````
(define (unzip rowsOfLists k)
    (apply map list (map (lambda (row) (take row k)) rowsOfLists)))
````

Sample Usage (http://ideone.com/uVaUf3):
````
(define (unzip rowsOfLists k)
    (apply map list (map (lambda (row) (take row k)) rowsOfLists)))

(define a (zip (iota 5 0) (iota 5 10) (iota 5 100)))
(display a)(newline)(newline)
(display (unzip a 0))(newline)
(display (unzip a 1))(newline)
(display (unzip a 2))(newline)
(display (unzip a 3))(newline)
````
Output:
````
((0 10 100) (1 11 101) (2 12 102) (3 13 103) (4 14 104))

()
((0 1 2 3 4))
((0 1 2 3 4) (10 11 12 13 14))
((0 1 2 3 4) (10 11 12 13 14) (100 101 102 103 104))
````

**Comment by arthurgleckler** [comment]
Hello, Francis.  Would you mind sending your message to
srfi-1@srfi.schemers.org?  That's the official discussion mailing list for
SRFI 1.  Github is just where the Git repositories are hosted.

Thanks.

**Comment by imfrancisd** [comment]
Ok.
Thanks!
